server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://db:5432/wizardpowers
    username: wizard
    password: powers
    driver-class-name: org.postgresql.Driver
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: wizardpowers
        dialect: org.hibernate.dialect.PostgreSQLDialect

#graphql:
#  servlet:
#    mapping: /wizardpowers